### ISSUE TITLE
Type-script erros wirth Angular

### ISSUE THREAD

**Issue by YevheniiStepaniuk** [Remmeauth/remme-client-js#13]
Recently, during hackathon faced with the issue when using `remme-client-js^0.3.3` with angular 6. Had some type-script errors that didn't allow to compile.

My node and npm versions: 
![node](https://user-images.githubusercontent.com/17275617/45742059-c28fe700-bc01-11e8-9044-438e8fc6c832.png)

Errors:
![untitl22ed](https://user-images.githubusercontent.com/17275617/45742763-5b733200-bc03-11e8-8bce-3b4152853ef5.png)

**Comment by ArtemFrantsiian** [comment]
Hello, thank you for your Issue, we changed documentation and provided steps for solving each kind of known errors. New documentation is available on the dev branch
